title: "HackHPC@ADMI26 Hackathon"

description: >
  SGX3's Association of Computer Science Departments at Minority
  Institutions (ADMI) Hackathon will take place virtually from
  June 22–26, 2026. Teams will focus on applying Science Gateway
  development skills as an extension of the ADMI 2026 Symposium on
  Computing at Minority Institutions theme, "Fine-Tuning AI Models."
  Pre-training activities have been provided in coordination with the
  SGX3 2026 Virtual Coding Institute.
